export interface StoreFullDto {
    name: string,
    address: string,
    city: string,
    state: string,
    zip: string,
    phone: string,
    circularPath: string,
    googleLocation: string,
    title: string,
    contactBtnLabel: string,
    hours: string,
    notes: string,
    logoLink: string,
    appKey: string,
    appSecret: string,
    storeId: string,
    storeDomain: string,
    pwaTitle: string,
    contentThreshold: string;
    googlePlaceId: string | string[],
    latitude: string,
    longitude: string,
}